# Site
name: "ISMRM Iberian Chapter"
title: "ISMRM Iberian Chapter"
description: "Website for the ISMRM Iberian Chapter"
meta_description: "Website for the ISMRM Iberian Chapter."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
email: 'e.urunuela@bcbl.eu'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge